name: ci-master

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: telescope-diff.nvim
          version: "Neovim >= 0.9.0"
          demojify: true
          treesitter: true
      - name: Commit and push changes
        shell: bash
        run: |
          set -e
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -n $(git status -s) ]]; then
            git diff
            git add .
            git commit -m "ci: update vimdoc"
            git push
          fi
